### ISSUE TITLE
Don't use Readme for Vuepress Doc Generation: polkadot-dev-build-docs

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/dev#365]
moved from https://github.com/polkadot-js/api/pull/2405

Currently relative paths in the README will break vuepress doc generation, and other way around as well.

So I will adjust the script to not use the README for building the docs, and generate that separately.

**Comment by jacogr** [comment]
Going to close this, we will be moving away from vuepress when there is a gap.
